### ISSUE TITLE
Unable to connect Robot ROS1 free_fleet client and PC ROS2 free_fleet server using Pocket Wifi.

### ISSUE THREAD

**Issue by suztakur** [open-rmf/free_fleet#122]
- Operating system and version: 
   PC: Ubuntu20.04, galactic robot: UbuntuMATE20.04, noetic

- How to install RMF
  I installed RMF following the guide in the link below.
https://github.com/open-rmf/free_fleet

### Description of the bug
　I started free_fleet_client on my robot's PC and free_fleet_server on my PC according to barebones example, but I can't connect.
I have confirmed the ping connection and port connection between the robot and the PC.
Both the robot and PC set ROS_DOMAIN_ID=0 and opened ports 7400~8000, which would be used by DDS, to check the connection.
Pocket Wifi is used as a common network.

### Steps to reproduce the bug
　PC: ROS_DOMAIN_ID=0, open ports 7400~8000 and start ff_examples_ros2 fake_server.launch.xml
　Robot: ROS_DOMAIN_ID=0, open ports 7400-8000 and run ff_examples_ros1 fake_client.launch.
　No connection.

### Expected behavior
　The free_fleet_client running on the robot is registered in the log of free_fleet_sever.

### Actual behavior
　No log is registered and no communication is established.

### Additional information
　Network settings were confirmed at the following link.
http://wiki.ros.org/ja/ROS/NetworkSetup
　The following link was used as a reference for opening the port.
https://docs.ros.org/en/foxy/Concepts/About-Domain-ID.html
　A Raspberry Pi 4 Model B is used as the robot PC.

**Comment by aaronchongth** [comment]
Hello there! Unfortunately I am unable to recreate this issue without the same hardware at hand. Some questions before I look further into it,

* Does this setup work when these 2 machines are on a different wifi?
* Does this setup work when these 2 machines are on a different pocket wifi?
* Does basic pub sub using ROS 1 or ROS 2 across this same network work? This will give us more information whether it is something that needs tweaking on the network level, cyclonedds or free fleet.
* If the above works, could you try your setup using basic pub sub on cyclonedds, https://github.com/eclipse-cyclonedds/cyclonedds/tree/master/examples?

Some things to note,
* since one of the machines is using ROS 1, setting `ROS_DOMAIN_ID` will not do anything, that is only useful for communications between ROS 2 machines.

I will be removing the `bug` label as this is not related to `free_fleet`'s implementation or our usage of `cyclonedds`, but rather the requirement of using a Pocket Wifi instead.

**Comment by suztakur** [comment]
Thanks for the reply.
I was able to confirm the connection by inactivating the firewalls on the robot PC and ROS2PC.
