### ISSUE TITLE
Extrapolation Error looking up target frame

### ISSUE THREAD

**Issue by pvg6** [open-rmf/free_fleet#156]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I didn't understand why i am getting this error...
I am working real turtlebot3 burger ..
distro: humble..

Integrating free fleet + Nav2 + RMF...

When i am launching the nav2 launch file there is no issue. the robot is coming with /tf data. when i am launching the rmf integrating for my turtlebot3 burger i am facing /tf issue and i am using legacy adapter...

Issue:  

```
[1730286957.967276893] [BehaviorTreeEngine]: Behavior Tree tick rate 100.00 was exceeded!
[rviz2-2] [INFO] [1730286958.019610947] [rviz2]: Message Filter dropping message: frame 'odom' at time 1730286946.434 for reason 'discarding message because the queue is full'
[component_container_isolated-1] [ERROR] [1730286958.068770214] [transformPoseInTargetFrame]: Extrapolation Error looking up target frame: Lookup would require extrapolation into the past.  Requested time 1730286937.225377 but the earliest data is at time 1730286939.134040, when looking up transform from frame [base_link] to frame [map]
[component_container_isolated-1] 
[component_container_isolated-1] [WARN] [1730286958.068925479] [BehaviorTreeEngine]: Behavior Tree tick rate 100.00 was exceeded!
[component_container_isolated-1] [ERROR] [1730286958.145212022] [transformPoseInTargetFrame]: Extrapolation Error looking up target frame: Lookup would require extrapolation into the past.  Requested time 1730286937.225377 but the earliest data is at time 1730286939.134040, when looking up transform from frame [base_link] to frame [map]
[component_container_isolated-1] 
[component_container_isolated-1] [ERROR] [1730286958.170215684] [transformPoseInTargetFrame]: Extrapolation Error looking up target frame: Lookup would require extrapolation into the past.  Requested time 1730286937.225377 but the earliest data is at time 1730286939.134040, when looking up transform from frame [base_link] to frame [map]
[component_container_isolated-1] 

```

I set use_sim_time:=false at all places...
Am i need to use zenoh bridge for sync or any other approach is there please help me...

**Comment by aaronchongth** [comment]
Hi @pvg6! Could you help describe your solution so it may help others who run into the same issue?

**Comment by aaronchongth** [comment]
The usage of zenoh bridges are mandatory but so far planned only for the new iteration of `free_fleet`, starting from https://github.com/open-rmf/free_fleet/pull/145.

If you're using the legacy version of `free_fleet` it still uses Cyclone DDS. Are you running a physical nav2 robot or in sim?

**Comment by pvg6** [comment]
@aaronchongth 

I am using the physical nav2 robot and I am using the rmf_demos_fleet_adapter.

**Comment by aaronchongth** [comment]
It looks like everything is actually in place, and working as expected. The difference between the 2 time stamps are 2~ seconds, `1730286937.225377` and `1730286939.134040` in the logs you provided. Also I noticed that the logs are from the Nav2 component containers, not from any RMF related nodes. This means that even without free_fleet and RMF, just by launching your nav2 setup, these logs are already happening. Can you confirm this?

Sanity check, just in case you're not doing it already, please run everything with `rmw_cyclonedds_cpp` too, https://docs.ros.org/en/jazzy/How-To-Guides/Working-with-multiple-RMW-implementations.html, i.e. `sudo apt install ros-$ROS_DISTRO-rmw-cyclonedds-cpp`  and running `export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp` before launching anything

There are also 2 other possibilities of why this is happening,
* the network latency is bad between your robot and other systems, you can try `rmw_cyclonedds_cpp` and see if it helps, otherwise you might need to do some monitoring and investigating on your own end
* there is a time difference between the robot and your other systems, this can happen if any of the systems are airgapped or have no access to sync their system clocks, setting up an NTP server on your network could help

**Comment by pvg6** [comment]
@aaronchongth 

I think it nav2 side issue only, I am bring up the not using docker humble.
But normal nav2 is working when I send the nav2goal but some time when I launch the RMF.  When it sends the goal to starting point there it is failing and automatically after some times it is failing and again coming ....

Like this I am facing...

**Comment by akash-roboticist** [comment]
@pvg6 can you open a [discussion](https://github.com/open-rmf/rmf/discussions) for this? Such chats are useful to build KB and out of scope for issues.
